=== Charbak/APMM-Microservice/GeoFeedScheduler/FixedLengthStringMessage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Robert Kurowski (SCS) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="message">
		<xs:annotation>
			<xs:documentation>Description of a fixed length string MQ message</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fieldDefinitions">
					<xs:annotation>
						<xs:documentation>All field declarations for this message type</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="defineField" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="valid" minOccurs="0" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>global valid values for this field</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="value" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="length" type="xs:integer" use="required"/>
									<xs:attribute name="type" type="xs:string" use="optional"/>
									<xs:attribute name="format" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="optional" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="tag" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="valid" minOccurs="0" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>local valid values for this field</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="value" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="optional" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="child" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="level" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="msgId" type="xs:string" use="required"/>
			<xs:attribute name="version" type="xs:string" use="required"/>
			<xs:attribute name="validate" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Charbak/APMM-Microservice/GeoFeedScheduler/GeoFeedMsgFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<message msgId="GEOFE001" version="000005" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FixedLengthStringMessage.xsd">
	<!-- global field definitions -->
	<fieldDefinitions>
		<!-- message header fields-->
		<defineField name="msgId" length="8" type="String"/>
		<defineField name="version" length="6" type="String"/>
		<defineField name="receiver" length="11" type="String">
			<valid value="ALL"/>
			<valid value="EDDI2"/>
		</defineField>
		<defineField name="ExtractTime" length="26" type="String" format="####-##-##-##.##.##.######"/>
		<defineField name="PrevExtractTime" length="26" type="String" format="####-##-##-##.##.##.######"/>
		<defineField name="MessageNumber" length="7" type="Numeric"/>
		<defineField name="EndMarker" length="1" type="String">
			<valid value="E"/>
			<valid value=" "/>
		</defineField>
		<defineField name="NumberOfRecords" length="4" type="Numeric"/>
		<!-- Country layout fields  -->
		<defineField name="Tag" length="6" type="String">
			<valid value="TAGA"/>
			<valid value="TAGB"/>
			<valid value="TAGC"/>
			<valid value="TAGD"/>
			<valid value="TAGE"/>
			<valid value="TAGX1"/>
			<valid value="TAGX2"/>
			<valid value="TAGX3"/>
			<valid value="TAGX4"/>
		</defineField>
		<defineField name="TransactionType" length="1" type="String">
			<valid value="I"/>
			<valid value="U"/>
			<valid value="D"/>
			<valid value="F"/>
		</defineField>
		<defineField name="GEOId" length="13" type="String"/>
		<defineField name="GEOCode" length="10" type="String"/>
		<defineField name="RKSTCode" length="8" type="String"/>
		<defineField name="RKTSCode" length="5" type="String"/>
		<defineField name="TypeOfLocation" length="35" type="String"/>
		<defineField name="UppercaseName" length="35" type="String"/>
		<defineField name="LocationName" length="36" type="String"/>
		<defineField name="Status" length="10" type="String"/>
		<defineField name="CodeForTimezone" length="4" type="String"/>
		<defineField name="DifferenceFromUTCTime" length="4" type="String"/>
		<defineField name="UppercaseNameForTheTimezone" length="35" type="String"/>
		<defineField name="NameOfTheTimezone" length="35" type="String"/>
		<defineField name="DaylightZoneCode" length="4" type="String"/>
		<defineField name="DaylightTimeDiff" length="4" type="String"/>
		<defineField name="DaylightSavingFromDate" length="8" type="Date" format="yyyyMMdd"/>
		<defineField name="DaylightSavingFromTime" length="6" type="Date" format="HHmmss"/>
		<defineField name="DaylightSavingToDate" length="8" type="Date" format="yyyyMMdd"/>
		<defineField name="DaylightSavingToTime" length="6" type="Date" format="HHmmss"/>
		<defineField name="DaylightSavingZoneUppercaseName" length="35" type="String"/>
		<defineField name="DaylightSavingZoneName" length="35" type="String"/>
		<defineField name="OmitAreaCode" length="1" type="String">
			<valid value="Y"/>
			<valid value="N"/>
		</defineField>
		<defineField name="PhoneInPrefix" length="4" type="String"/>
		<defineField name="PhoneOutPrefix" length="4" type="String"/>
		<defineField name="TelexInPrefix" length="4" type="String"/>
		<defineField name="PostcodePredefined" length="1" type="String">
			<valid value="Y"/>
			<valid value="N"/>
		</defineField>
		<defineField name="PostcodeMandatory" length="1" type="String">
			<valid value="Y"/>
			<valid value="N"/>
		</defineField>
		<defineField name="PostcodeuniqueInCountry" length="1" type="String">
			<valid value="Y"/>
			<valid value="N"/>
		</defineField>
		<defineField name="PostcodePrefix" length="2" type="String"/>
		<defineField name="DialAreaPrefix" length="4" type="String"/>
		<defineField name="DCDate" length="26" type="Date" format="yyyy-MM-dd-HH.mm.ss.SSS"/>
		<defineField name="CHDate" length="26" type="Date" format="yyyy-MM-dd-HH.mm.ss.SSS"/>
		<defineField name="DCUser" length="8" type="String"/>
		<defineField name="CHUser" length="8" type="String"/>
		<!-- State / Province layout fields -->
		<defineField name="FIPSCode" length="4" type="String"/>
		<defineField name="RKSTCountryCode" length="2" type="String"/>
		<defineField name="RKTSCountryCode" length="3" type="Numeric"/>
		<defineField name="CountryGEOId" length="13" type="String"/>
		<defineField name="CountryName" length="36" type="String"/>
		<!-- City/Subcity layout fields  -->
		<defineField name="UNLoCode" length="5" type="String"/>
		<defineField name="RKCCLocationCode" length="5" type="String"/>
		<defineField name="Longitude" length="11" type="Numeric"/>
		<defineField name="Latitude" length="11" type="Numeric"/>
		<defineField name="CityCode" length="2" type="String"/>
		<defineField name="CityGEOId" length="13" type="String"/>
		<defineField name="CityName" length="36" type="String"/>
		<defineField name="StateCode" length="2" type="String"/>
		<defineField name="StateGEOId" length="13" type="String"/>
		<defineField name="StateName" length="36" type="String"/>
		<defineField name="ContinentCode" length="3" type="String"/>
		<defineField name="ContinentName" length="14" type="String"/>
		<defineField name="TimeZone" length="3" type="String"/>
		<defineField name="PoolCode" length="8" type="String"/>
		<defineField name="PoolName" length="36" type="String"/>
		<defineField name="RegionCode" length="3" type="String"/>
		<defineField name="RegionName" length="14" type="String"/>
		<defineField name="ValidityDate" length="8" type="String"/>
		<defineField name="AreaCode" length="3" type="String"/>
		<defineField name="MetropolitanArea" length="5" type="String"/>
		<defineField name="Online" length="1" type="String"/>
		<defineField name="DropNearestCY" length="1" type="String"/>
		<defineField name="RelatedCY1" length="8" type="String"/>
		<defineField name="RelatedCY1DistanceKM" length="4" type="Numeric"/>
		<defineField name="RelatedCY1DistanceInMiles" length="4" type="Numeric"/>
		<defineField name="RelatedCY2" length="8" type="String"/>
		<defineField name="RelatedCY2DistanceKM" length="4" type="Numeric"/>
		<defineField name="RelatedCY2DistanceInMiles" length="4" type="Numeric"/>
		<defineField name="RelatedCY3" length="8" type="String"/>
		<defineField name="RelatedCY3DistanceKM" length="4" type="Numeric"/>
		<defineField name="RelatedCY3DistanceInMiles" length="4" type="Numeric"/>
		<defineField name="RelatedCFS1" length="8" type="String"/>
		<defineField name="RelatedCFS1DistanceKM" length="4" type="Numeric"/>
		<defineField name="RelatedCFS1DistanceInMiles" length="4" type="Numeric"/>
		<defineField name="RelatedCFS2" length="8" type="String"/>
		<defineField name="RelatedCFS2DistanceKM" length="4" type="Numeric"/>
		<defineField name="RelatedCFS2DistanceInMiles" length="4" type="Numeric"/>
		<defineField name="RelatedCFS3" length="8" type="String"/>
		<defineField name="RelatedCFS3DistanceKM" length="4" type="Numeric"/>
		<defineField name="RelatedCFS3DistanceInMiles" length="4" type="Numeric"/>
		<defineField name="Area" length="1" type="String"/>
		<defineField name="AMC" length="1" type="String"/>
		<defineField name="DCC" length="3" type="String"/>
		<defineField name="DocumentationCenter" length="3" type="String"/>
		<defineField name="Telex" length="8" type="String"/>
		<defineField name="Printer1" length="4" type="String"/>
		<defineField name="Printer2" length="4" type="String"/>
		<defineField name="FeederPort" length="3" type="String"/>
		<defineField name="PortFlag" length="1" type="String"/>
		<defineField name="Overdue" length="2" type="String"/>
		<defineField name="LineCompany" length="3" type="String"/>
		<defineField name="PayAtPort" length="1" type="String"/>
		<defineField name="PayPort" length="3" type="String"/>
		<defineField name="PortDefinedForCAMIR" length="1" type="String"/>
		<defineField name="DatePortDefinedForCAMIR" length="8" type="Date" format="yyyyMMdd"/>
		<defineField name="AllowedRKDSLOPDIPMSK" length="1" type="String">
			<valid value="Y"/>
			<valid value=" "/>
			<valid value="L"/>
			<valid value="D"/>
		</defineField>
		<defineField name="AllowedRKDSLOPDIPSCL" length="1" type="String">
			<valid value="Y"/>
			<valid value=" "/>
			<valid value="L"/>
			<valid value="D"/>
		</defineField>
		<defineField name="AllowedRKDSRECDELMSK" length="2" type="String">
			<valid value="Y"/>
			<valid value="N"/>
			<valid value="R"/>
			<valid value="D"/>
			<valid value="C"/>
			<valid value="F"/>
			<valid value="A"/>
			<valid value="B"/>
			<valid value="L"/>
			<valid value="E"/>
			<valid value="G"/>
			<valid value="H"/>
			<valid value="I"/>
			<valid value="K"/>
			<valid value="M"/>
			<valid value="O"/>
		</defineField>
		<defineField name="AllowedRKDSRECDELSCL" length="1" type="String">
			<valid value="Y"/>
			<valid value="N"/>
			<valid value="R"/>
			<valid value="D"/>
			<valid value="C"/>
			<valid value="F"/>
			<valid value="A"/>
			<valid value="B"/>
			<valid value="L"/>
			<valid value="E"/>
			<valid value="G"/>
			<valid value="H"/>
			<valid value="I"/>
			<valid value="K"/>
			<valid value="M"/>
			<valid value="O"/>
		</defineField>
		<defineField name="CYSupported" length="1" type="String">
			<valid value="Y"/>
			<valid value="N"/>
			<valid value=" "/>
		</defineField>
		<defineField name="ValidInRKMSOnly" length="1" type="String">
			<valid value="X"/>
			<valid value=" "/>
		</defineField>
		<!-- Site layout fields -->
		<defineField name="Street1" length="36" type="String"/>
		<defineField name="Street2" length="36" type="String"/>
		<defineField name="City" length="36" type="String"/>
		<defineField name="CityNearSiteCode" length="10" type="String"/>
		<defineField name="CityNearSiteGEOId" length="13" type="String"/>
		<!-- BDA layout fields -->
		<defineField name="BDAId" length="13" type="String"/>
		<defineField name="BDA_NAME" length="40" type="String"/>
		<defineField name="BDA_CODE" length="10" type="String"/>
		<defineField name="BDA_TYPE_CODE" length="10" type="String"/>
